# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [7]:
### [your code here]
import numpy as np     



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.version.version)

1.26.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
### [your code here]  
# 2x3x5 2 bloques cada bloque tiene 3 filas y cada columna tiene 5 columnas [[[]]]
#a = np.random.randint(np.random.random_integers(100), size=(2, 3, 5))
a = np.random.randint(1, 500, size=(2, 3, 5))
a
a = np.random.random_sample((2, 3, 5))

rng = np.random.default_rng(seed=42) # create instance of default random number generator
a = rng.random((2, 3, 5))
a


a = np.empty((2, 3, 5))
a




array([[[0.53782924, 0.93815208, 0.32398505, 0.26343694, 0.15152364],
        [0.72136164, 0.62832707, 0.25073579, 0.03635819, 0.54843412],
        [0.09383006, 0.50321624, 0.48038074, 0.91106712, 0.81348021]],

       [[0.70554242, 0.20032569, 0.85820224, 0.02605015, 0.64427888],
        [0.1327339 , 0.92351357, 0.72202301, 0.71923805, 0.29168876],
        [0.19635812, 0.19414602, 0.91498996, 0.80270444, 0.23541585]]])


### 4. Print a.


In [98]:
a

array([[[0.53782924, 0.93815208, 0.32398505, 0.26343694, 0.15152364],
        [0.72136164, 0.62832707, 0.25073579, 0.03635819, 0.54843412],
        [0.09383006, 0.50321624, 0.48038074, 0.91106712, 0.81348021]],

       [[0.70554242, 0.20032569, 0.85820224, 0.02605015, 0.64427888],
        [0.1327339 , 0.92351357, 0.72202301, 0.71923805, 0.29168876],
        [0.19635812, 0.19414602, 0.91498996, 0.80270444, 0.23541585]]])

In [22]:
### [your code here]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [103]:
### [your code here]
b = np.ones((5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 6. Print b.


In [104]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
### [your code here]
len(a) == len(b)


5


### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
a + b

### I am not able to do it as they are not of the same shapes 


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [128]:
### [your code here]
# As I want to pass from 5x2x3 to 2x3x5 this means that: (index 1: 2, index 2: 3, index 0: 5)
# ask Isabella which one is better
c = b.transpose(1, 2, 0)
c
d = np.transpose(b, (1, 2, 0))
d

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [131]:
### [your code here]
a
d = a + c
d

array([[[1.53782924, 1.93815208, 1.32398505, 1.26343694, 1.15152364],
        [1.72136164, 1.62832707, 1.25073579, 1.03635819, 1.54843412],
        [1.09383006, 1.50321624, 1.48038074, 1.91106712, 1.81348021]],

       [[1.70554242, 1.20032569, 1.85820224, 1.02605015, 1.64427888],
        [1.1327339 , 1.92351357, 1.72202301, 1.71923805, 1.29168876],
        [1.19635812, 1.19414602, 1.91498996, 1.80270444, 1.23541585]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [135]:
### [your code here]
print(a)
print('\n')
print(d)
# The difference between a and d is that d has a values +1 because we obtained d adding a + an array of ones. The difference is that every element of d is bigger on 1 from a
# The relation is that both have the same shape this is because we obtained d from the sum of a + 1, adding two arrays of the same shape

[[[0.53782924 0.93815208 0.32398505 0.26343694 0.15152364]
  [0.72136164 0.62832707 0.25073579 0.03635819 0.54843412]
  [0.09383006 0.50321624 0.48038074 0.91106712 0.81348021]]

 [[0.70554242 0.20032569 0.85820224 0.02605015 0.64427888]
  [0.1327339  0.92351357 0.72202301 0.71923805 0.29168876]
  [0.19635812 0.19414602 0.91498996 0.80270444 0.23541585]]]


[[[1.53782924 1.93815208 1.32398505 1.26343694 1.15152364]
  [1.72136164 1.62832707 1.25073579 1.03635819 1.54843412]
  [1.09383006 1.50321624 1.48038074 1.91106712 1.81348021]]

 [[1.70554242 1.20032569 1.85820224 1.02605015 1.64427888]
  [1.1327339  1.92351357 1.72202301 1.71923805 1.29168876]
  [1.19635812 1.19414602 1.91498996 1.80270444 1.23541585]]]



### 12. Multiply a and c. Assign the result to e.


In [140]:
### [your code here]
e = a*c
print(e)
print(a)
e == a

[[[0.53782924 0.93815208 0.32398505 0.26343694 0.15152364]
  [0.72136164 0.62832707 0.25073579 0.03635819 0.54843412]
  [0.09383006 0.50321624 0.48038074 0.91106712 0.81348021]]

 [[0.70554242 0.20032569 0.85820224 0.02605015 0.64427888]
  [0.1327339  0.92351357 0.72202301 0.71923805 0.29168876]
  [0.19635812 0.19414602 0.91498996 0.80270444 0.23541585]]]
[[[0.53782924 0.93815208 0.32398505 0.26343694 0.15152364]
  [0.72136164 0.62832707 0.25073579 0.03635819 0.54843412]
  [0.09383006 0.50321624 0.48038074 0.91106712 0.81348021]]

 [[0.70554242 0.20032569 0.85820224 0.02605015 0.64427888]
  [0.1327339  0.92351357 0.72202301 0.71923805 0.29168876]
  [0.19635812 0.19414602 0.91498996 0.80270444 0.23541585]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 13. Does e equal to a? Why or why not?


In [142]:
### [your code here]
# I guess a is in fact equal to e, as c is an array of ones and multiplying it to a returns the same array as a. So we end up with e, that is an array of the same shape and values that a
np.array_equal(a, e)
np.all(a == e)


True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)



1.9381520784884527 1.0260501546312222 1.4923109720907264



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [150]:
### [your code here]
f = np.empty((2, 3, 5))
f

array([[[0.53782924, 0.93815208, 0.32398505, 0.26343694, 0.15152364],
        [0.72136164, 0.62832707, 0.25073579, 0.03635819, 0.54843412],
        [0.09383006, 0.50321624, 0.48038074, 0.91106712, 0.81348021]],

       [[0.70554242, 0.20032569, 0.85820224, 0.02605015, 0.64427888],
        [0.1327339 , 0.92351357, 0.72202301, 0.71923805, 0.29168876],
        [0.19635812, 0.19414602, 0.91498996, 0.80270444, 0.23541585]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [161]:
### [your code here]
print(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
print(f)

[[[1.53782924 1.93815208 1.32398505 1.26343694 1.15152364]
  [1.72136164 1.62832707 1.25073579 1.03635819 1.54843412]
  [1.09383006 1.50321624 1.48038074 1.91106712 1.81348021]]

 [[1.70554242 1.20032569 1.85820224 1.02605015 1.64427888]
  [1.1327339  1.92351357 1.72202301 1.71923805 1.29168876]
  [1.19635812 1.19414602 1.91498996 1.80270444 1.23541585]]]
[[[ 75. 100.  25.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 75.  25.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [162]:

print(d)
print(f)

[[[1.53782924 1.93815208 1.32398505 1.26343694 1.15152364]
  [1.72136164 1.62832707 1.25073579 1.03635819 1.54843412]
  [1.09383006 1.50321624 1.48038074 1.91106712 1.81348021]]

 [[1.70554242 1.20032569 1.85820224 1.02605015 1.64427888]
  [1.1327339  1.92351357 1.72202301 1.71923805 1.29168876]
  [1.19635812 1.19414602 1.91498996 1.80270444 1.23541585]]]
[[[ 75. 100.  25.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 75.  25.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [171]:
### [your code here]
e = np.empty_like(f, dtype=object)
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if f[i][j][k] == 0.:
                e[i][j][k] = 'A'
            elif f[i][j][k] == 25.:
                e[i][j][k] = 'B'
            elif f[i][j][k] == 50.:
                e[i][j][k] = 'C'
            elif f[i][j][k] == 75.:
                e[i][j][k] = 'D'
            elif f[i][j][k] == 100.:
                e[i][j][k] = 'E'